### PR TITLE
Mapping filters, resource pack stuff and completing world mappings

### PR DESCRIPTION
**Pull request by viktor40**
I also fixed some build errors from gradle

### CODE REVIEW

**Comment by KayleighWasTaken** [comment]
Pretty sure that `class_2609` isn't IUnzippedResourcePack, the class that inherits it deals with zipped resource packed data it looks like?

**Comment by viktor40** [comment]
> Pretty sure that `class_2609` isn't IUnzippedResourcePack, the class that inherits it deals with zipped resource packed data it looks like?

I will look at that class again today

**Comment by viktor40** [comment]
You are correct, i switched it to `IZipResourcePakck` I also changed `UnzippedResourcePack` to `AnonZipResourcePack` because there is already a base class for a resource pack as zip `ZipResourcePack` and for a resource pack as folder `DirectoryResourcePack`

**Comment by KayleighWasTaken** [comment]
> You are correct, i switched it to `IZipResourcePakck` I also changed `UnzippedResourcePack` to `AnonZipResourcePack` because there is already a base class for a resource pack as zip `ZipResourcePack` and for a resource pack as folder `DirectoryResourcePack`. It also makes a lot more sense to download a resource pack as zip then as a folder xd.

I almost prefer `UnzippedResourcePack` to `DirectoryResourcePack` but honestly that's neither here nor there, leave it as is.

**Comment by viktor40** [comment]
> > You are correct, i switched it to `IZipResourcePakck` I also changed `UnzippedResourcePack` to `AnonZipResourcePack` because there is already a base class for a resource pack as zip `ZipResourcePack` and for a resource pack as folder `DirectoryResourcePack`. It also makes a lot more sense to download a resource pack as zip then as a folder xd.
> 
> I almost prefer `UnzippedResourcePack` to `DirectoryResourcePack` but honestly that's neither here nor there, leave it as is.

I also added a javadocs explaining what a `DirectoryResourcePack` is, because I also found the name slightly confusing.

**Review by Copetan — APPROVED** [review]

**Pull request merged**
