### PR TITLE
Additional class mappings

### PR DESCRIPTION
**Pull request by NotCreative21**
Some of these may need a quick glance over, it's relatively few additions

### CODE REVIEW

**Comment by KayleighWasTaken** [comment]
OK here goes with the review:
`class_2305` is not a menu, it is an abstract class used by the resource pack menu widgets/buttons. In my PR it is mapped to `AbstractResourcePackEntryWidget`.

`class_2304` is potentially dubious but it's not that bad.

`class_2303` is also not a menu, it's the menu entry widget used in the server list.

`class_2523` is a raw packet, not a handler. I also thought that you remapped it correctly to be a packet?

`class_2313` is named reasonably appropriately.

**Review by viktor40 — CHANGES_REQUESTED** [review]
After deliberation with @KayleighWasTaken we implemented the feedback from [the previous comment](https://github.com/Copetan/feather-mappings/pull/35#issuecomment-1002246554).

- [ ] Remap `class_2303` to the correct name `ServerListEntryWidget`
       `Class_2303` is one server entry in the server list and is a widget that displays the server icon, ping etc. Hence Server, List, Entry and Widget
- [ ] I would remap `class_2304` to `PingServerRunnnable`
       The class pings the server, gets the ping and if it is not able to ping it will throw an error. We add `Runnable` at the end to make it consistent with other anonymous classes. See for example the anonymous classes implementing `Callable` or extending `Thread`
- [ ] Unmap `class_2305` to avoid conflicts with #31

**Review by KayleighWasTaken — CHANGES_REQUESTED** [review]
OK here goes with the review:
`class_2305` is not a menu, it is an abstract class used by the resource pack menu widgets/buttons. In my PR it is mapped to `AbstractResourcePackEntryWidget`. Advise to remove from PR as mine is more complete.

`class_2304` is a runnable which pings servers for `class_2303`, should be changed to something like `PingServerRunnable`

`class_2303` is a `ListEntry` based menu widget which represents a server in the server list, should be changed to something like `ServerListEntryWidget`

`class_2523` is `KeyHandlerC2SPacket` according to the logs you submitted on Discord, not sure why it is mapped differently in this PR, should be changed.

`class_2313` is named reasonably appropriately I think, not going to advise any changes on that.

**Review by KayleighWasTaken — APPROVED** [review]
Looks good to me now :+1:

**Review by Copetan — APPROVED** [review]

**Pull request merged**
