### PR TITLE
Update player inventory and scoreboard

### PR DESCRIPTION
**Pull request by Grohiik**
PlayerInventory changes  
Scoreboard changes

### CODE REVIEW

**Comment by Grohiik** [comment]
@KayleighWasTaken This is where you argue for addToScoreboard

**Comment by Grohiik** [comment]
The argument

Kayleigh
Alt text]

Grohiik
Alt text]

**Comment by KayleighWasTaken** [comment]
`method_2111` => `addToScore` / `addScore`
`method_2114` => `subtractFromScore` / `subtractScore`
`method_2110` => `incrementScore`

My justification for this is that `method_2111` is improperly named as `incrementScore` as it adds an arbitrary integer to the score, and the world increment implies a fixed addition of one in most contexts which could lead to ambiguity when there is a method which explicitly adds one to a score. My names are also slightly more concise in my opinion.

**Comment by Grohiik** [comment]
> 

And my justification is that Increment as a word is improperly used when referring too increments by one

**Comment by KayleighWasTaken** [comment]
@viktor40 also petitioned in VC for `method_2111` => `increaseScore` and `method_2114` => `decreaseScore` which are also pretty good mappings in my opinion.

**Comment by KayleighWasTaken** [comment]
> > 
> 
> And my justification is that Increment as a word is improperly used when referring too increments by one

My justification is also that applying the term increment to an arbitrary increase in quantity is improper usage.
Also:
javaisclikerightxd

**Comment by Grohiik** [comment]
> method_2111 => addToScore / addScore
method_2114 => subtractFromScore / subtractScore
method_2110 => incrementScore

I'd probably be ok with addOneToScore instead of incrementScore

**Review by Copetan — APPROVED** [review]

**Pull request merged**
